/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsReportingRouteImport } from './routes/products/reporting'
import { Route as ProductsCoreMoneyRouteImport } from './routes/products/core-money'
import { Route as ProductsCashManagementRouteImport } from './routes/products/cash-management'
import { Route as ProductsCapitalCallsRouteImport } from './routes/products/capital-calls'
import { Route as ProductsBillPayRouteImport } from './routes/products/bill-pay'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsReportingRoute = ProductsReportingRouteImport.update({
  id: '/products/reporting',
  path: '/products/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCoreMoneyRoute = ProductsCoreMoneyRouteImport.update({
  id: '/products/core-money',
  path: '/products/core-money',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCashManagementRoute = ProductsCashManagementRouteImport.update({
  id: '/products/cash-management',
  path: '/products/cash-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCapitalCallsRoute = ProductsCapitalCallsRouteImport.update({
  id: '/products/capital-calls',
  path: '/products/capital-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBillPayRoute = ProductsBillPayRouteImport.update({
  id: '/products/bill-pay',
  path: '/products/bill-pay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/bill-pay': typeof ProductsBillPayRoute
  '/products/capital-calls': typeof ProductsCapitalCallsRoute
  '/products/cash-management': typeof ProductsCashManagementRoute
  '/products/core-money': typeof ProductsCoreMoneyRoute
  '/products/reporting': typeof ProductsReportingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/bill-pay': typeof ProductsBillPayRoute
  '/products/capital-calls': typeof ProductsCapitalCallsRoute
  '/products/cash-management': typeof ProductsCashManagementRoute
  '/products/core-money': typeof ProductsCoreMoneyRoute
  '/products/reporting': typeof ProductsReportingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/bill-pay': typeof ProductsBillPayRoute
  '/products/capital-calls': typeof ProductsCapitalCallsRoute
  '/products/cash-management': typeof ProductsCashManagementRoute
  '/products/core-money': typeof ProductsCoreMoneyRoute
  '/products/reporting': typeof ProductsReportingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/products/bill-pay'
    | '/products/capital-calls'
    | '/products/cash-management'
    | '/products/core-money'
    | '/products/reporting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/products/bill-pay'
    | '/products/capital-calls'
    | '/products/cash-management'
    | '/products/core-money'
    | '/products/reporting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/products/bill-pay'
    | '/products/capital-calls'
    | '/products/cash-management'
    | '/products/core-money'
    | '/products/reporting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsBillPayRoute: typeof ProductsBillPayRoute
  ProductsCapitalCallsRoute: typeof ProductsCapitalCallsRoute
  ProductsCashManagementRoute: typeof ProductsCashManagementRoute
  ProductsCoreMoneyRoute: typeof ProductsCoreMoneyRoute
  ProductsReportingRoute: typeof ProductsReportingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/reporting': {
      id: '/products/reporting'
      path: '/products/reporting'
      fullPath: '/products/reporting'
      preLoaderRoute: typeof ProductsReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/core-money': {
      id: '/products/core-money'
      path: '/products/core-money'
      fullPath: '/products/core-money'
      preLoaderRoute: typeof ProductsCoreMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cash-management': {
      id: '/products/cash-management'
      path: '/products/cash-management'
      fullPath: '/products/cash-management'
      preLoaderRoute: typeof ProductsCashManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/capital-calls': {
      id: '/products/capital-calls'
      path: '/products/capital-calls'
      fullPath: '/products/capital-calls'
      preLoaderRoute: typeof ProductsCapitalCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/bill-pay': {
      id: '/products/bill-pay'
      path: '/products/bill-pay'
      fullPath: '/products/bill-pay'
      preLoaderRoute: typeof ProductsBillPayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsBillPayRoute: ProductsBillPayRoute,
  ProductsCapitalCallsRoute: ProductsCapitalCallsRoute,
  ProductsCashManagementRoute: ProductsCashManagementRoute,
  ProductsCoreMoneyRoute: ProductsCoreMoneyRoute,
  ProductsReportingRoute: ProductsReportingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
